version: '3'

services:

  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    ports: # Ports will be exposed to the host machine to a random port or a given port. Like NodePort in Kubernetes
      - 9090:9090
    volumes:
      - ./monitor/prometheus/config:/etc/prometheus
      - ./monitor/prometheus/prometheus-data:/prometheus-data

  node-exporter:
    image: prom/node-exporter:v1.1.2
    container_name: node_exporter
    restart: unless-stopped
    expose: # Ports are not exposed to host machines, only exposed to other services. Like ClusterIP in Kubernetes
      - 9100

  grafana:
    image: grafana/grafana:7.5.3
    container_name: grafana
    volumes:
      - ./monitor/grafana/grafana-data/grafana:/var/lib/grafana
    ports:
      - 3030:3000
    user: "472"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_USERS_ALLOW_SIGN_UP=false
#      - GF_SERVER_DOMAIN=myrul.com
#      - GF_SMTP_ENABLED=true
#      - GF_SMTP_HOST=smtp.gmail.com:587
#      - GF_SMTP_USER=myadrress@gmail.com
#      - GF_SMTP_PASSWORD=mypassword
#      - GF_SMTP_FROM_ADDRESS=myaddress@gmail.com
